// lib/parks/lake-tahoe/index.ts
// Lake Tahoe Basin — all campground, trail, and amenity data
// matching the same ParkCampsite / ParkTrail / ParkAmenity types
// used by the 5 national parks.

import type { ParkCampsite, ParkTrail, ParkAmenity } from '@/components/ParkMap';

export const TAHOE_CAMPGROUNDS: ParkCampsite[] = [
  { id:'dlbliss',       name:'D.L. Bliss State Park',              lat:38.9695, lng:-120.1035, facilityId:undefined, sites:168, hookups:false, res:true,  fee:35, desc:'West shore classic. Rubicon Trail access and stunning lake views. Open mid-June through Labor Day.',       url:'https://reservecalifornia.com/park/637',                                                    system:'ReserveCalifornia' },
  { id:'eaglepoint',    name:'Emerald Bay — Eagle Point',          lat:38.9540, lng:-120.1060, facilityId:undefined, sites:97,  hookups:false, res:true,  fee:35, desc:'Inside Emerald Bay State Park. The most scenic campground at Tahoe. Walk to Vikingsholm and Fannette Island.', url:'https://reservecalifornia.com/park/641',                                                    system:'ReserveCalifornia' },
  { id:'sugarpine',     name:'Sugar Pine Point — General Creek',   lat:39.0418, lng:-120.1120, facilityId:undefined, sites:175, hookups:false, res:true,  fee:35, desc:'West shore pine forest campground. Access to General Creek Trail and cross-country skiing in winter.',       url:'https://www.parks.ca.gov/?page_id=510',                                                     system:'ReserveCalifornia' },
  { id:'fallenleaf',    name:'Fallen Leaf Lake Campground',        lat:38.8980, lng:-120.0540, facilityId:'232769',  sites:206, hookups:false, res:true,  fee:30, desc:'Secluded lake south of Tahoe. Access to Desolation Wilderness. Tent and RV sites, flush toilets.',           url:'https://www.recreation.gov/camping/campgrounds/232769',                                     system:'Recreation.gov' },
  { id:'nvbeach',       name:'Nevada Beach Campground',            lat:38.9630, lng:-119.9280, facilityId:'232768',  sites:54,  hookups:false, res:true,  fee:32, desc:'East shore sandy beach campground. Best beach access of any campground at the lake. Nevada side.',          url:'https://www.recreation.gov/camping/campgrounds/232768',                                     system:'Recreation.gov' },
  { id:'williamkent',   name:'William Kent Campground',            lat:39.0895, lng:-120.1340, facilityId:'232874',  sites:95,  hookups:false, res:true,  fee:32, desc:'North of Tahoe City on Hwy 89. Short walk to the lake. Close to Tahoe City amenities and bike trail.',     url:'https://www.recreation.gov/camping/campgrounds/232874',                                     system:'Recreation.gov' },
  { id:'meeksbay',      name:'Meeks Bay Resort & Campground',      lat:39.0226, lng:-120.1182, facilityId:'10220612',sites:77,  hookups:true,  res:true,  fee:42, desc:'West shore with direct beach access. Boat ramp, kayak rentals, and hookups. Open May through October.',     url:'https://www.recreation.gov/camping/campgrounds/10220612',                                   system:'Recreation.gov' },
  { id:'zephyr',        name:'Zephyr Cove RV & Campground',        lat:38.9945, lng:-119.9390, facilityId:'10300216',sites:149, hookups:true,  res:true,  fee:45, desc:'East shore with RV hookups, beach, and boat rentals. Most amenity-rich campground at Tahoe.',              url:'https://www.recreation.gov/camping/campgrounds/10300216',                                   system:'Recreation.gov' },
  { id:'camprich',      name:'Camp Richardson — RV Village',       lat:38.9345, lng:-120.0485, facilityId:'10305470',sites:98,  hookups:true,  res:true,  fee:55, desc:'South shore resort campground with restaurant, marina, watersports, and ice cream parlor.',                url:'https://www.recreation.gov/camping/campgrounds/10305470',                                   system:'Recreation.gov' },
  { id:'kaspian',       name:'Kaspian Campground',                 lat:39.0978, lng:-120.1612, facilityId:'232875',  sites:9,   hookups:false, res:true,  fee:27, desc:'9 tent-only walk-in sites 4 miles south of Tahoe City. Nestled in ponderosa pine across Hwy 89 from the lake.', url:'https://www.recreation.gov/camping/campgrounds/232875',                                   system:'Recreation.gov' },
  { id:'tahoe-sra',     name:'Tahoe State Recreation Area',        lat:39.1720, lng:-120.1465, facilityId:undefined, sites:23,  hookups:false, res:true,  fee:35, desc:'23 sites on Hwy 28 in Tahoe City. Walk to lake, restaurants, and the bike trail. Open May through October.', url:'https://www.parks.ca.gov/?page_id=504',                                                     system:'ReserveCalifornia' },
  { id:'lake-forest',   name:'Lake Forest Campground',             lat:39.1778, lng:-120.1342, facilityId:undefined, sites:20,  hookups:false, res:false, fee:25, desc:'First-come, first-served TCPUD campground north of Tahoe City. Boat ramp adjacent. Tent only.',              url:'https://www.tcpud.org/parks-facilities/facilities-parks-and-rentals/lake-forest-campground', system:'First-Come · TCPUD' },
  { id:'spooner',       name:'Spooner Backcountry Campgrounds',    lat:39.1020, lng:-119.9080, facilityId:undefined, sites:15,  hookups:false, res:false, fee:15, desc:'East shore Nevada State Parks backcountry sites. Access to Marlette Lake and Flume Trail. First-come.',      url:'https://parks.nv.gov/parks/spooner-lake',                                                   system:'First-Come · NV State Parks' },
  { id:'campground-by-the-lake', name:'Campground by the Lake',   lat:38.9274, lng:-119.9742, facilityId:undefined, sites:170, hookups:true,  res:true,  fee:39, desc:'City of South Lake Tahoe campground. RV hookups, tent sites, and walking distance to Stateline casinos.',  url:'https://www.cityofslt.gov/270/Campground-by-the-Lake',                                      system:'City of South Lake Tahoe' },
];

export const TAHOE_TRAILS: ParkTrail[] = [
  // ── Signature Hikes ──────────────────────────────────────────────────────
  { id:'mount-tallac',        name:'Mount Tallac',                     lat:38.9127, lng:-120.0978, difficulty:'Expert',   distanceMi:9.4,  elevGainFt:3295, desc:'The most iconic summit hike at Tahoe — 9.4 miles RT with 3,295 ft gain to a 9,735 ft peak. Cross-shaped snowfield visible from the lake. Desolation Wilderness permit required overnight.', note:'Wilderness permit required for overnight' },
  { id:'eagle-falls',         name:'Eagle Falls & Eagle Lake',         lat:38.9538, lng:-120.1093, difficulty:'Moderate', distanceMi:2.0,  elevGainFt:400,  desc:'The most popular short hike in Tahoe. Emerald Bay viewpoint, waterfall, and Eagle Lake in 2 miles. Crowded in summer — arrive before 9am. Permit required on weekends.' },
  { id:'vikingsholm',         name:'Vikingsholm Trail',                lat:38.9536, lng:-120.1086, difficulty:'Easy',     distanceMi:2.0,  elevGainFt:320,  desc:'Paved trail down to Vikingsholm Castle on Emerald Bay — a 38-room Scandinavian manor built in 1929. Open for tours in summer. Best Tahoe viewpoint of Emerald Bay.' },
  { id:'cascade-falls',       name:'Cascade Falls',                    lat:38.9333, lng:-120.0622, difficulty:'Easy',     distanceMi:1.6,  elevGainFt:200,  desc:'Short 1.6 mile RT to a 200 ft waterfall above Cascade Lake. Best in spring snowmelt. Roadside parking off Hwy 89 south of Emerald Bay.' },
  { id:'rubicon',             name:'Rubicon Trail',                    lat:38.9738, lng:-120.1030, difficulty:'Moderate', distanceMi:5.0,  elevGainFt:800,  desc:'West shore gem from D.L. Bliss to Emerald Bay — 5 miles of cliff-edge trail with dramatic lake views 600 feet above the surface. One of the best non-summit hikes in the Sierra.' },
  { id:'glen-alpine',         name:'Glen Alpine Trailhead — Desolation',lat:38.8932, lng:-120.0540, difficulty:'Moderate', distanceMi:10.0, elevGainFt:1800, desc:'Main access to Desolation Wilderness from the south. Passes Gilmore Lake and Susie Lake. Overnight permit required for camping in the wilderness.' },
  { id:'echo-lake',           name:'Echo Lake — JMT Access',           lat:38.8305, lng:-120.0367, difficulty:'Moderate', distanceMi:26.0, elevGainFt:2800, desc:'Water taxi across Echo Lake to access the John Muir Trail and Desolation Wilderness. One-way multi-day route to Yosemite for experienced backpackers.' },
  { id:'tahoe-east-shore',    name:'East Shore Trail',                 lat:39.1610, lng:-119.9900, difficulty:'Easy',     distanceMi:4.2,  elevGainFt:100,  desc:'Paved flat trail along the Nevada east shore from Spooner Summit. Mountain bike and hike access to Sand Harbor. Car-free and family friendly.' },
  // ── Rim Trail ─────────────────────────────────────────────────────────────
  { id:'trt-tahoe-city',      name:'Tahoe Rim Trail — Tahoe City',     lat:39.1718, lng:-120.1452, difficulty:'Moderate', distanceMi:165.0, elevGainFt:24400, desc:'The complete 165-mile Tahoe Rim Trail circumnavigates the entire basin. Tahoe City is the main trailhead and start/end point. Multi-day thru-hike or day sections.' },
  { id:'stateline-lookout',   name:'Stateline Lookout',                lat:39.2373, lng:-120.0198, difficulty:'Easy',     distanceMi:1.5,  elevGainFt:180,  desc:'Easy north shore trail to a dramatic viewpoint above Kings Beach and Crystal Bay. 1.5 miles RT. One of the best bang-for-effort views at the lake.' },
  { id:'five-lakes',          name:'Five Lakes Trail',                 lat:39.1908, lng:-120.2178, difficulty:'Moderate', distanceMi:4.6,  elevGainFt:1000, desc:'Granite Chief Wilderness trail to five alpine lakes above Alpine Meadows. 4.6 miles RT, 1,000 ft gain. Dogs allowed. One of the most rewarding moderate hikes.' },
  { id:'mount-rose-summit',   name:'Mount Rose Summit',                lat:39.3133, lng:-119.9182, difficulty:'Strenuous', distanceMi:10.9, elevGainFt:2395, desc:'Highest easily accessible peak near Lake Tahoe at 10,776 ft. 10.9 miles RT. Nevada side — no parking fee. Expansive views of both Tahoe and Reno.' },
  { id:'marlette-flume',      name:'Marlette Lake / Flume Trail',      lat:39.0955, lng:-119.9080, difficulty:'Strenuous', distanceMi:22.0, elevGainFt:3200, desc:'The legendary east shore Flume Trail — 22 miles of singletrack along a historic water flume with vertiginous lake views. Serious MTB route also open to hikers.' },
  // ── MTB Trails ───────────────────────────────────────────────────────────
  { id:'flume-trail-mtb',     name:'Flume Trail (MTB)',                lat:39.0955, lng:-119.9080, difficulty:'Strenuous', distanceMi:22.0, elevGainFt:3200, desc:"Tahoe's most famous mountain bike trail. 22 miles of exposed singletrack carved into a cliff face above the east shore. Shuttle recommended. World-class." },
  { id:'corral-trail',        name:'South Shore MTB — Corral Trail Hub',lat:38.9212, lng:-120.0302, difficulty:'Moderate', distanceMi:5.0,  elevGainFt:700,  desc:'South shore mountain bike network centered on the Corral Trail. Mix of flowy singletrack and technical sections. Good for intermediate riders.' },
  { id:'burton-creek',        name:'Burton Creek State Park MTB',      lat:39.1900, lng:-120.1350, difficulty:'Easy',     distanceMi:20.0, elevGainFt:800,  desc:'North Tahoe\'s best beginner-friendly MTB network. 20 miles of dirt roads and trails through pine forest. No parking fee. Great for families.' },
  { id:'martis-valley',       name:'Martis Valley Trail System',       lat:39.2750, lng:-120.1500, difficulty:'Moderate', distanceMi:35.0, elevGainFt:1500, desc:'Rolling high-valley trail system north of Truckee. 35+ miles of singletrack through volcanic terrain. Access from several trailheads. No fee.' },
];

export const TAHOE_AMENITIES: ParkAmenity[] = [
  // ── Visitor Centers / Ranger Stations ────────────────────────────────────
  { id:'fs-visitor-center',   name:'USFS Lake Tahoe Visitor Center',   lat:38.9345, lng:-120.0485, type:'viewpoint', desc:'South shore USFS visitor center at Camp Richardson. Stream Profile Chamber, nature trail, and ranger programs. Free.' },
  { id:'tahoe-rim-assoc',     name:'Tahoe Rim Trail Association',      lat:39.1695, lng:-120.1470, type:'viewpoint', desc:'Tahoe Rim Trail info, maps, and trail conditions. Based in Tahoe City. Best resource for TRT planning.' },
  // ── Gear & Outfitters ─────────────────────────────────────────────────────
  { id:'rei-slt',             name:'REI — South Lake Tahoe',           lat:38.9310, lng:-119.9780, type:'rental', desc:'Full outfitter — climbing gear, hiking boots, backpacking gear, kayaks. Expert staff. South shore.', url:'https://www.rei.com' },
  { id:'alpenglow',           name:'Alpenglow Sports — Truckee',       lat:39.3275, lng:-120.1837, type:'rental', desc:'Best gear shop near North Tahoe. Climbing, skiing, and hiking gear. Expert local route beta. Truckee.', url:'https://alpenglowsports.com' },
  { id:'tahoe-outdoor-center',name:'Tahoe Outdoor Center',             lat:39.1690, lng:-120.1490, type:'rental', desc:'Kayak, SUP, and bike rentals. Tahoe City. Lake access. Great for water sports and trail bikes.', url:'https://www.tahoeoutdoorcenter.com' },
  { id:'shoreline-mtb',       name:'Shoreline MTB Shop — SLT',         lat:38.9380, lng:-119.9820, type:'rental', desc:'South shore mountain bike shop. Rentals, repairs, and local trail knowledge. Close to Corral Trail.', url:'https://www.shorelinemtb.com' },
  { id:'flume-trail-bikes',   name:'Flume Trail Bikes — Incline',      lat:39.2540, lng:-119.9382, type:'rental', desc:'Full suspension MTB rentals and shuttle for the Flume Trail. Only shuttle service on the east shore.', url:'https://flumetrailbikes.com' },
  // ── Water Sports ─────────────────────────────────────────────────────────
  { id:'tahoe-paddle',        name:'Tahoe Paddle & Oar — Kings Beach', lat:39.2360, lng:-120.0230, type:'rental', desc:'Kayak, SUP, and pedal boat rentals. Kings Beach. North shore lake access. Lessons available.', url:'https://www.tahoepaddle.com' },
  { id:'zephyr-cove-marina',  name:'Zephyr Cove Marina',               lat:38.9940, lng:-119.9390, type:'rental', desc:'Boat rentals, parasailing, kayak, and paddle boards. East shore. Closest marina to Stateline.', url:'https://www.zephyrcove.com' },
  { id:'camp-rich-watersports',name:'Camp Richardson Watersports',     lat:38.9345, lng:-120.0485, type:'rental', desc:'Kayak, SUP, canoe, and bike rentals at Camp Richardson. South shore. Beach access.', url:'https://camprichardson.com' },
  // ── Lodging ───────────────────────────────────────────────────────────────
  { id:'camp-rich-resort',    name:'Camp Richardson Resort',           lat:38.9345, lng:-120.0485, type:'spot', desc:'Historic south shore resort. Cabins, RV sites, tent camping, restaurant, ice cream parlor, and marina.', url:'https://camprichardson.com' },
  { id:'tahoe-city-lodge',    name:'Tahoe City Inn & Restaurants',     lat:39.1690, lng:-120.1490, type:'spot', desc:'Tahoe City dining, lodging, and services. Bike trail access. North shore hub.' },
  // ── Grocery ───────────────────────────────────────────────────────────────
  { id:'safeway-slt',         name:'Safeway — South Lake Tahoe',       lat:38.9188, lng:-119.9765, type:'viewpoint', desc:'Full grocery store. Open late. South shore main supply point before camping trips.' },
  { id:'safeway-tahoe-city',  name:'Safeway — Tahoe City',             lat:39.1682, lng:-120.1468, type:'viewpoint', desc:'Full grocery store. North shore. Camp supply before heading to west shore campgrounds.' },
];
